services:
  link_shortener_frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: link_shortener_frontend
    image: link_shortener_frontend
    environment:
      - BACKEND_DOCKER_URL=${BACKEND_DOCKER_URL}
    ports:
      - "${EXTERNAL_PORT}:80"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy

networks:
  proxy:
    external: true
